application: slim-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /slim.manifest
  mime_type: text/cache-manifest
  static_files: static/slim.manifest
  upload: static/slim.manifest
- url: /static/images/(.*)@2x\.(.*)
  static_files: static/images/\1_2x.\2
  upload: static/images/.*_2x.*
- url: /static
  static_dir: static
- url: .*
  script: main.py
